services:

  postgres:
    container_name: postgres
    image: postgres:16.2
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database

  backend:
    container_name: boiler_plate_nest_app
    build:
      context: .
      dockerfile: Dockerfile
      target: app_node
    volumes:
      - ./:/src/app
    ports:
      - "9229:9229"
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://user:password@postgres:5433/database?serverVersion=16.2
      APP_PORT: 8000
      API_DOC: 'TRUE'
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      JWT_SECRET: TopSecret
    
    command: "npm run start:dev"